// Generated by CoffeeScript 1.3.3
(function() {

  console.log("window.location", window.location);

  $.getJSON("/cs-intro/test.json", function(data) {
    return $("#app_container").append(data.test);
  });

}).call(this);
