// Generated by CoffeeScript 1.3.3
(function() {

  $("#app_container").append("Test");

  console.log("window.location", window.location);

  $.getJSON("/cs-intro/test.json", function(data) {
    return console.log("test.json", data);
  });

}).call(this);
