// Generated by CoffeeScript 1.3.3
(function() {
  var getBlab, htmlNode;

  getBlab = function() {
    var blab, css, h, p, query;
    query = location.search.slice(1);
    if (!query) {
      return null;
    }
    h = query.split("&");
    p = h != null ? h[0].split("=") : void 0;
    blab = p.length && p[0] === "blab" ? p[1] : null;
    if (!blab) {
      return null;
    }
    css = $("<link>", {
      rel: "stylesheet",
      type: "text/css",
      href: "/" + blab + "/main.css"
    });
    $(document.head).append(css);
    return $.get("/" + blab + "/main.html", function(data) {
      return $("#codeout_html").append(Wiky.toHtml(data));
    });
  };

  htmlNode = function() {
    var html;
    html = "<div id=\"code_nodes\" data-module-id=\"b00cv\">\n<div class=\"code_node_container\" id=\"code_node_container_html\" data-node-id=\"html\" data-filename=\"main.html\">\n	<div class=\"code_node_output_container\" id=\"output_html\">\n		<div class=\"code_node_html_output\" id=\"codeout_html\"></div>\n	</div>\n</div>\n</div>";
    return $("#app_container").append(html);
  };

  htmlNode();

  getBlab();

}).call(this);
