// Generated by CoffeeScript 1.3.3

/*
Puzlet Bootstrap
*/


(function() {
  var a, host, isLocalHost, loadScript, loaderPath, loaderUrl, localLoaderUrl, localOrg, puzletLoaderUrl, puzletOrg;

  localOrg = "../../puzlet";

  puzletOrg = "http://puzlet.org";

  loaderPath = "/puzlet/js/loader.js";

  if (window.console == null) {
    window.console = {};
  }

  if (window.console.log == null) {
    window.console.log = (function() {});
  }

  console.log("Puzlet bootstrap");

  a = document.createElement("a");

  a.href = window.location.href;

  host = a.hostname;

  isLocalHost = host === "localhost";

  localLoaderUrl = localOrg + loaderPath;

  puzletLoaderUrl = puzletOrg + loaderPath;

  loaderUrl = isLocalHost ? localLoaderUrl : puzletLoaderUrl;

  loadScript = function(url, onError) {
    var script;
    script = document.createElement("script");
    script.setAttribute("type", "text/javascript");
    script.setAttribute("src", url);
    script.onerror = onError;
    return document.head.appendChild(script);
  };

  console.log("Attempting to load " + loaderUrl + " (localhost).");

  loadScript(loaderUrl, function() {
    console.log("No loader.js found on localserver.  Loading " + puzletLoaderUrl + ".");
    return loadScript(puzletLoaderUrl, function() {});
  });

}).call(this);
